// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehgjdkganantnvngrusj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZ2pka2dhbmFudG52bmdydXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzIxOTMsImV4cCI6MjA2NjE0ODE5M30.2FG33dqUsVeN05KHRMZUFVqBi8yr6AXX3bDGafw7cmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);